### ISSUE TITLE
Graph4NLP Text classification

### ISSUE THREAD

**Issue by SanketTijare** [graph4ai/graph4nlp#340]
## ❓ Questions and Help

You have added this "Graph Convolutional Networks for Text Classification" paper to the Literature, did you also implemented this with graph4Nlp. [link] : (https://ojs.aaai.org//index.php/AAAI/article/view/4725)

Also, is there a way so that we can build our own Graph/Topology or any example/demo where we can see that.

**Comment by hugochan** [comment]
> ## ❓ Questions and Help
> You have added this "Graph Convolutional Networks for Text Classification" paper to the Literature, did you also implemented this with graph4Nlp. [link] : (https://ojs.aaai.org//index.php/AAAI/article/view/4725)
> 
> Also, is there a way so that we can build our own Graph/Topology or any example/demo where we can see that.

@SanketTijare Thanks for your interest to the graph4nlp library! We did not implement the AAAI19 paper you mentioned. But we do have a text classification implementation in our example code ([link](https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/text_classification)). 

Yes, you can build your own graph construction module by inheriting `StaticGraphConstructionBase` ([example](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py#L12)) or `DynamicGraphConstructionBase ` ([example](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/graph_construction/node_embedding_based_graph_construction.py#L14)).

Hope this helps.

**Comment by SanketTijare** [comment]
@hugochan Thanks for the quick response. 

I was going through the paper, and it has its different topology to build the graph. They have solved the text-classification as Node Classification, so was wondering if you have some examples on similar lines. Are you planning to implement that topology, else need to build my own with inheriting `StaticGraphConstructionBase`.

**Comment by hugochan** [comment]
> @hugochan Thanks for the quick response.
> 
> I was going through the paper, and it has its different topology to build the graph. They have solved the text-classification as Node Classification, so was wondering if you have some examples on similar lines. Are you planning to implement that topology, else need to build my own with inheriting `StaticGraphConstructionBase`.

@SanketTijare As you mentioned, that paper constructed a single graph for the whole corpus and performed node classification. Because this is kind of application-driven and we want to prioritize major improvements because of limited budget, unfortunately, we are not planning to implement their approach in the near future. 

Hopefully, it should be straightforward to build your own graph topology builder and node classification model. You might find this [node classification example](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/test/node_classification/node_classification_test.py) and [KG completion example](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/kg_completion/WN18RR_main.py) helpful. BTW, you are welcome to contribute to the library if you decide to implement their approach.

Hope this helps.

**Comment by AlanSwift** [comment]
I will close this issue.

**Comment by isspek** [comment]
Thank you so much for the library, it would be really helpful for researchers. My question is similar to the first question. I am interested in the evaluation of the following paper: https://arxiv.org/abs/2004.13826 The paper is inductive, so each split has its own graph structure. I wonder how one can implement this paper with the library. I would be happy if you could answer. Thank you
