### ISSUE TITLE
How load vocabulary

### ISSUE THREAD

**Issue by maurovit** [graph4ai/graph4nlp#347]
## ❓ Questions and Help
Hello, 
I noticed that everytime i start the network graph2tree (on jobs dataset) the network needs to read all the trainset to build the vocabulary, that is very time-consuming as process. How could I load vocabulary in a faster way without the need of training set?
Thank you

**Comment by schenglee** [comment]
Hi, we have fixed it in #331 in the ``develop`` branch, you just need to reinstall the library from that branch.

**Comment by maurovit** [comment]
Hello,
first of all, thank you. I have a doubt, I hope that you can help me: as I said previously I need to load vocab so that I can avoid the time spent to rebuild it at the building of the network but I need also to make inference in a way that is similar to the following

`pred = model.predict('Some sentence')`

how can I do that, or which branch I can refer to do this? Cause now I'm doing inference with a workaround using a couple like
`Some Inference Sentence <TBD>`
in test.txt file, so that the model preprocess the data in test.txt file at the start of the model and make its predictions. Now I need something to do this in real time and not with a fake way.
Thank you 🙏

**Comment by AlanSwift** [comment]
We are really sorry for the inconvenience. We know that this is an urgent issue we need to solve.
In our plan, this is the **NEXT TODO** feature.
TODO 1: Currently, we plan to lint the code (add some CI) and the documentation (especially the user-guide) and we will release it in the next version in one month. In addition, we will come up with a compromise solution, which use only testing data and the model checkpoint to do the inference (see "develop" branch).
TODO 2: Then we will improve the inference API and support "pred = model.predict('Some sentence')". In the mean time, we will also modify the design to better support this feature so it will a big progress.

We are sorry that the inference API will come in about two month, maybe it is late for you. We sincerely hope you can understand our difficulty since we are all students volunteering to do that. 

Thank you again for your kind advice!

**Comment by maurovit** [comment]
It's not a problem, thank you for your reply. It's a great work.
Maybe if you can give me suggestions about things that I can modify to implement the inference process (maybe extending or overriding some methods) I will be very grateful.

**Comment by AlanSwift** [comment]
Sure. You are welcome to contribute to this project! We highly appreciate your interest and efforts! 
I can give you a brief introduction about the pipeline: "output = mode.predict(sentence or list of sentences)". 
1. call ``self.graph_topology`` to build the raw graph data topology.
2. call the vectorization in the [dataset](https://github.com/graph4ai/graph4nlp/blob/c10007afb54c0d84170cdbaac1d4d65d2d08ac06/graph4nlp/pytorch/data/dataset.py#L730). 
3. call the ``collate_fn`` in the dataset, which will conduct ``to_batch`` and other data collate procedures. 
4. do the ``prepare_ext_vocab`` if ``use_copy`` is enabled.
5. do the forward calculation
This is my plan and I am responsible for this feature. Please feel free to contact me if you are interested.

**Comment by AlanSwift** [comment]
I will reopen this issue.

**Comment by AlanSwift** [comment]
This problem is solved and I will close this issue.
