### ISSUE TITLE
Running on colab

### ISSUE THREAD

**Issue by icocoder** [graph4ai/graph4nlp#457]
## ❓ Questions and Help

Due to the fact that there is only sequential cells in the free version of colab, and the requirement of running stanford corenlp, I was wondering if there is way to run the examples on it. 
There is stanza (official corenlp wrapper for python), but I don't know which parts of the codes should be changed to make it run properly. 

Thanks in advance.

**Comment by AlanSwift** [comment]
Hi.
I think the graph construction method should be rewritten. The link is [https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py#L57](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py#L57).

**Comment by icocoder** [comment]
Hi, thanks for your response. 
I tried to implement this part again but I had some issues. The first thing that I'm wondering is 
when I comment out all the codes in this method (parsing) the code still tries to connect to stanford corenlp. 
I guess maybe some other parts needs to be rewritten.

**Comment by icocoder** [comment]
I have another question. May I ask what was the specs of the system that you have used to run the provided examples? 

thanks in advance.

**Comment by AlanSwift** [comment]
Reply to Q1:
I guess you have run the codes with the wrong version.  Since Stanford CoreNLP is only called in this [line](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py#L92). Please check it.
Reply to Q2:
You can refer to semantic parsing example: [semantic parsing](https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/semantic_parsing/graph2seq).

**Comment by AlanSwift** [comment]
I will close this issue and please feel free to reopen if you still have trouble.
