### ISSUE TITLE
Graph Isomorphism Network

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#489]
Do you plan to support Graph Isomorphism Network (GIN)?

- [HOW POWERFUL ARE GRAPH NEURAL NETWORKS?](https://arxiv.org/pdf/1810.00826.pdf)

**Comment by AlanSwift** [comment]
Currently, we don't plan to support it. However, it's not difficult to customize and pr is welcomed :) !

**Comment by nashid** [comment]
Ok, I will try to look into it.

**Comment by hugochan** [comment]
@nashid Thanks for your attention to the library! We are not planning to support GIN in the short term because we rarely see GIN applications on NLP tasks. Please let us know if you are aware of any interesting NLP applications using GIN.

Closed the issue as of now. Please feel free to reopen it or send a PR.
