### ISSUE TITLE
BPE for the NMT example

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#551]
## ❓ Questions and Help

I see in the given example `BPE` is removed during [evaluation](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/nmt/main.py#L233):

```
 pred_collect.extend(self.remove_bpe(pred_str))
```

remove BPE code:
```
    def remove_bpe(self, str_with_subword):
        if isinstance(str_with_subword, list):
            return [self.remove_bpe(ss) for ss in str_with_subword]
        symbol = "@@ "
        return str_with_subword.replace(symbol, "").strip()
```

But where are you applying `BPE` during vocab building?

**Comment by AlanSwift** [comment]
Yes. The raw data are tokenized by BPE.

**Comment by smith-co** [comment]
@AlanSwift can you please help me with the query?

**Comment by AlanSwift** [comment]
The current NMT example is using BPE since the BPE is a good practice and is widely used in the NMT community. Technically it is OK if you want to use the whole words as your vocabulary in your own application. However, your vocabulary will be large if you do it. What's more, the performance may be limited by the OOV(out of vocabulary problem).
